// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9IJ2hsVz7xCi5zR5KCVLs7tDEc8QcVvU',
    appId: '1:853829300850:web:4658dc1fd9e07f86b408eb',
    messagingSenderId: '853829300850',
    projectId: 'new-travel-app-a8441',
    authDomain: 'new-travel-app-a8441.firebaseapp.com',
    storageBucket: 'new-travel-app-a8441.appspot.com',
    measurementId: 'G-S34C7GSGP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5HtQKXyW5hs7VGYTVYlA-ZBBU1ZI4ZNw',
    appId: '1:853829300850:android:aec5a4de275dd556b408eb',
    messagingSenderId: '853829300850',
    projectId: 'new-travel-app-a8441',
    storageBucket: 'new-travel-app-a8441.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPa-LBxBuXx2uooWE610nO1wTxy3YhsA',
    appId: '1:853829300850:ios:87f1c5a0ec48b6c1b408eb',
    messagingSenderId: '853829300850',
    projectId: 'new-travel-app-a8441',
    storageBucket: 'new-travel-app-a8441.appspot.com',
    iosBundleId: 'com.example.flutterAppNew1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApPa-LBxBuXx2uooWE610nO1wTxy3YhsA',
    appId: '1:853829300850:ios:957a205d44bee5b6b408eb',
    messagingSenderId: '853829300850',
    projectId: 'new-travel-app-a8441',
    storageBucket: 'new-travel-app-a8441.appspot.com',
    iosBundleId: 'com.example.flutterAppNew1.RunnerTests',
  );
}
